src/reachy2_sdk/reachy_sdk.py
tests/units/online/test_basic_movements.py

Unit tests are now working again

290 unit tests failure

---

src/examples/2_moves_introduction.ipynb
src/examples/3_arm_and_gripper.ipynb
src/examples/4_head_control.ipynb
src/reachy2_sdk/orbita/orbita.py
src/reachy2_sdk/parts/arm.py
src/reachy2_sdk/parts/head.py
src/reachy2_sdk/reachy_sdk.py
tests/units/offline/test_arm.py
tests/units/offline/test_head.py
tests/units/online/test_advanced_goto_functions.py

Based on #288 
set_pose() is now possible even if parts are off.
Add set_pose() to parts.
Goto does not raise error anymore fi they are off, error is replaced by a warning.
Closes #273

272 set position does not work if head is turned off

---

src/reachy2_sdk/reachy_sdk.py
tests/units/offline/test_reachy_sdk.py

Add warnings everywhere in case of disconnection

317 handle connection problems

---

src/reachy2_sdk/parts/arm.py
src/reachy2_sdk/parts/head.py
src/reachy2_sdk/parts/joints_based_part.py

We should have only `set_torque_limits()` and `set_speed_limits()`.
The duplicated methods have been removed.

Fix duplicated method

---

setup.cfg
src/reachy2_sdk/parts/arm.py
src/reachy2_sdk/parts/hand.py
src/reachy2_sdk/parts/joints_based_part.py
src/reachy2_sdk/reachy_sdk.py
tests/units/offline/test_hand.py
tests/units/online/test_hand.py

Possibility to send goal_position to gripper instead of opening.
Te be used with:
- reachy2-sdk-api : https://github.com/pollen-robotics/reachy2-sdk-api/pull/134
- reachy2_sdk_server : https://github.com/pollen-robotics/reachy2_sdk_server/pull/159
Can be used doing :
```python
reachy.r_arm.gripper.goal_position = 40
reachy.send_goal_positions()
```

331 control hand in position

---

src/reachy2_sdk/orbita/orbita.py
src/reachy2_sdk/parts/arm.py
src/reachy2_sdk/parts/hand.py
src/reachy2_sdk/parts/head.py
src/reachy2_sdk/parts/mobile_base.py
src/reachy2_sdk/parts/part.py
src/reachy2_sdk/reachy_sdk.py
tests/units/online/test_audit.py

We can get errors on the actuators of the robot with `reachy.audit`, on parts with `reachy.r_arm.audit` or directly on the actuator itself with `reachy.r_arm.shoulder.audit`
audit is called in background every seconds to update potential errors

328 add audit function

---

README.md
setup.cfg
src/examples/1_getting_started.ipynb
src/examples/2_moves_introduction.ipynb
src/examples/3_arm_and_gripper.ipynb
src/examples/4_head_control.ipynb
src/examples/5_cameras_images.ipynb
src/examples/6_mobile_base.ipynb
src/examples/cameras.py
src/reachy2_sdk/media/camera.py
src/reachy2_sdk/media/camera_manager.py
tests/units/offline/test_camera.py
tests/units/online/test_camera.py

requirements:
core image https://github.com/pollen-robotics/docker_reachy2_core/pull/100
with 
- SDK API: https://github.com/pollen-robotics/reachy2-sdk-api/pull/137
- core: https://github.com/pollen-robotics/reachy2_core/pull/74
- sdk server: https://github.com/pollen-robotics/reachy2_sdk_server/pull/164
to test you can run the unit tests
`pytest -m cameras`
and the notebook 5, and the cameras.py example

349 integrate orbbec

---

src/reachy2_sdk/orbita/orbita_joint.py
src/reachy2_sdk/parts/arm.py
src/reachy2_sdk/parts/goto_based_part.py
src/reachy2_sdk/parts/head.py
src/reachy2_sdk/reachy_sdk.py
tests/units/online/test_advanced_goto_functions.py

Instead of doing: 
```python
a = reachy.r_arm.goto_joints([...])
while not reachy.is_move_finished(a):
time.sleep(0.1)
``` 
We can do:
```python
reachy.r_arm.goto_joints([...], wait=True)
```

380 be able to wait for movements

---

src/reachy2_sdk/parts/hand.py
tests/units/online/conftest.py
tests/units/online/test_hand.py

We have to find a name close to `is_move_finished()` but which does not confuse the user that moving the gripper is not a move returning an id etc...

371 add function to know if gripper has finished movement

---

src/reachy2_sdk/parts/arm.py
src/reachy2_sdk/reachy_sdk.py

Modify turn_off_smoothly to have the same behavior as within the teleop app.
:warning: WARNING : Not tested on the real robot so far

384 turn off smoothly could be smooth

---

src/reachy2_sdk/parts/arm.py
src/reachy2_sdk/parts/head.py

Add logger.error if we use `send_goal_positions()` on a part that is off

388 check is off before all send goal positions

---

src/examples/2_moves_introduction.ipynb
src/examples/3_arm_and_gripper.ipynb
src/examples/6_mobile_base.ipynb
src/reachy2_sdk/media/camera.py

based on #401 
It can be tested with something like
```
pos = reachy.cameras.teleop.pixel_to_world(720,720, 1, CameraView.LEFT)
reachy.head.look_at(pos[0], pos[1], pos[2])
```
Actually it can work for @ClaireHzl 's example.

403 look at in pixel space

---

src/examples/1_getting_started.ipynb
src/examples/2_goto_introduction.ipynb
src/examples/2_moves_introduction.ipynb
src/examples/3_arm_and_gripper.ipynb
src/examples/4_head_control.ipynb
src/examples/6_mobile_base.ipynb
src/examples/draw_square.py
src/examples/set_zero_pose.py
src/reachy2_sdk/parts/arm.py
src/reachy2_sdk/parts/goto_based_part.py
src/reachy2_sdk/parts/head.py
src/reachy2_sdk/parts/mobile_base.py
src/reachy2_sdk/reachy_sdk.py
tests/integration/test_goto.py
tests/units/offline/test_head.py
tests/units/offline/test_reachy_sdk.py
tests/units/online/conftest.py
tests/units/online/test_advanced_goto_functions.py
tests/units/online/test_basic_movements.py
tests/units/online/test_hand.py
tests/units/online/test_multiple_connections.py

Modifications : 
- get_move_playing --> get_goto_playing
- get_moves_queue --> get_goto_queue
- cancel_all_moves --> cancel_all_goto
- cancel_move_by_id --> cancel_goto_by_id
- orient --> goto_quat
- set_pose --> goto_posture

408 modify function names from move into goto

---

src/examples/2_goto_introduction.ipynb
src/examples/3_arm_and_gripper.ipynb
src/examples/4_head_control.ipynb
src/examples/draw_square.py

Switch from timesleep with .is_goto_finished to wait=True in the notebooks

412 modify way to wait for movements in notebooks

---

.github/workflows/docs.yml
.github/workflows/lint.yml
.github/workflows/publish_pypi.yml
.github/workflows/unit_tests.yml
setup.cfg

Test coverage was not covering the whole project

fix coverage report

---

src/reachy2_sdk/reachy_sdk.py

This reverts commit 9f50337d39f2ac44701f43753bb5585ca69402cf.

Revert "Change cameras warning for FAKE mode"

---

src/reachy2_sdk/orbita/orbita.py
src/reachy2_sdk/orbita/utils.py
src/reachy2_sdk/parts/arm.py
src/reachy2_sdk/parts/goto_based_part.py
src/reachy2_sdk/parts/hand.py
src/reachy2_sdk/parts/head.py
src/reachy2_sdk/parts/joints_based_part.py
src/reachy2_sdk/parts/mobile_base.py
src/reachy2_sdk/parts/part.py
tests/units/offline/test_arm.py
tests/units/offline/test_custom_dict.py
tests/units/offline/test_hand.py
tests/units/offline/test_head.py
tests/units/offline/test_mobile_base.py
tests/units/offline/test_orbita2d.py
tests/units/offline/test_orbita3d.py
tests/units/offline/test_orbita_utils.py
tests/units/offline/test_reachy.py
tests/units/offline/test_reachy_sdk.py
tests/units/offline/test_utils.py
tests/units/online/conftest.py

438 increase test coverage ratio

---

setup.cfg
src/examples/1_getting_started.ipynb
src/examples/6_audio.ipynb
src/examples/7_mobile_base.ipynb
src/reachy2_sdk/media/audio.py
src/reachy2_sdk/reachy_sdk.py
tests/units/offline/test_orbita_axis.py
tests/units/offline/test_orbita_motor.py
tests/units/online/test_audio.py

The docker image 1.7.4.1 is required. The audio server will start automatically with the SDK server.
There is a notebook to test the audio features

483 audio features

---

setup.cfg
src/reachy2_sdk/__init__.py
src/reachy2_sdk/config/reachy_info.py

Add checks on the used api version:
- check if the currently used api satisfies the requirements
- inform a new version of the sdk may be available if used api is higher than minimal requirements
- check the lcoally used api is the same as the robot api

Check remote api version

---

tests/units/online/test_advanced_goto_functions.py
tests/units/online/test_basic_movements.py
tests/units/online/test_hand.py
tests/units/online/test_interpolations.py
tests/units/online/test_mobile_base.py
tests/units/online/test_send_goal_positions.py

The tests should almost always pass, except the goal_status still at Unkown sometimes.

526 fix unit tests
