setup.cfg, src/reachy2_sdk/config/reachy_info.py, src/reachy2_sdk/parts/mobile_base.py
We do not use Mobile base SDK anymore, but it was still imported in ReachyInfo
=> Remove definitively MobileBaseSDK

tests/units/online/test_camera.py
Minor fix of the unit test related to the change to ROS system.
Camera is always "on" from the SDK point of view. But get_frame and get_parameters will return None
=> 325 unit test assert camera name=teleop stereo=true is none

src/reachy2_sdk/parts/mobile_base.py, src/reachy2_sdk/sensors/lidar.py
The lidar safety could not be set because the grpc stub MobileBaseUtilityServiceStub was used to call the grpc method SetZuuuSafety instead of MobileBaseLidarServiceStub.
I added safety_distance and critical_distance as optional arguments as sending a LidarSafety message without them would set their value to 0.0 which is then interpreted as request to 0.0 in the zuuu hal. I you prefer @glannuzel not to let the user the ability to change these values from the sdk level we can also always send the safety and critical distances attributes of the Lidar object.
=> 322 lidar safety cannot be set

src/reachy2_sdk/orbita/orbita2d.py, src/reachy2_sdk/orbita/orbita3d.py, tests/units/online/test_basic_movements.py
- Fix the problem: messages were sent even when _outgoing_goal_positions was empty
- Add test using both arms at the same time with send_goal_positions
Can be tested with `pytest -k test_send_goal_positions`
=> 345 bug with send goal positions on both arms

src/examples/3_arm_and_gripper.ipynb
Modify notebook 3_arm_and_gripper to introduce `rotate_by()`, `translate_by()`, `get_rotation_by()` and `get_translation_by()`
=> Add translation and rotation examples

src/reachy2_sdk/reachy_sdk.py, tests/units/online/test_actuators_properties.py
Add function to reinit the values of speed and torque limits on the robot
Call `reachy.reset_default_limits()` to set back speed and torque limits to 100
Note : tests do not work as head returns "inf" for speed and torque limits on fake robot.
=> 347 add init function

src/reachy2_sdk/parts/arm.py, tests/integration/test_goto.py
It was too dangerous to have *with_cartesian_interpolation* has an argument of the goto_from_matrix(), has it is not a goto and resolve in the same conflicts as sending gotos and goal_positions at the same time if used with other goto_from_matrix() with the argument set at False.
=> 287  goto cartesian interpolation incompatibility

src/reachy2_sdk/parts/hand.py, src/reachy2_sdk/parts/joints_based_part.py, src/reachy2_sdk/parts/mobile_base.py, src/reachy2_sdk/parts/part.py, src/reachy2_sdk/reachy_sdk.py
Using `reachy.turn_on()` should be smoother than before, as we reduce speed limits to 1% before turning on.
=> Modify speeds on turn_on

src/examples/cameras.py, src/reachy2_sdk/media/camera.py, src/reachy2_sdk/utils/utils.py, tests/units/offline/test_utils.py
Requires these two repos:
https://github.com/pollen-robotics/reachy2-sdk-api/pull/144
https://github.com/pollen-robotics/reachy2_sdk_server/pull/174
@ClaireHzl can you test if it actually works by modifying your example (https://github.com/pollen-robotics/demo_month/blob/demo_fruits/notebook_fruits.ipynb)
```
T_cam_world = reachy.cameras.depth.get_extrinsics()
T_world_cam = invert_affine_transformation_matrix(T_cam_world)
```
=> 397 expose cameras extrinsic matrix

src/reachy2_sdk/parts/arm.py, src/reachy2_sdk/reachy_sdk.py, src/reachy2_sdk/utils/utils.py, tests/units/offline/test_utils.py, tests/units/online/test_basic_movements.py
Add of 2 utils functions to create matrix pose for the arms : 
- `reachy.r_arm.get_default_pose_matrix()`, which takes the same common_pose as `set_pose()`
- `reachy.r_arm.get_pose_matrix([x, y, z], [roll, pitch, yaw])` to create matrix the way they use `make_pose` in the tuto
Not sure arm.py is the right place.
=> 391 add utils functions for pose matrix

src/reachy2_sdk/parts/arm.py, src/reachy2_sdk/utils/utils.py, tests/units/offline/test_utils.py, tests/units/online/test_interpolations.py
This one is not ready for merge, but I would like some inputs.
The idea: we can do linear or elliptic interpolation in cartesian space, so that the trajectory of the end effector is known, unlike with goto_joints or goto_from_matrix (interpolations are in joint space for both).
We can call `reachy.r_arm.send_cartesian_interpolation(target_pose, duration)` to do so, with by default a linear interpolation.
Using `reachy.r_arm.send_cartesian_interpolation(target_pose, duration, circular_interpolation=True, arc_direction='below')` makes a circular interpolation and chooses the arc in -z direction normal to the vector current/target pose. *arc_direction* can be : `below`, `above`, `right`, `left`, `front` or `back`. (if the arc has no solution, does linear interpolation instead)
Last option is …
=> Circular interpolation

src/reachy2_sdk/parts/mobile_base.py, tests/units/online/test_advanced_goto_functions.py
Add new functions `reachy.mobile_base.translate_by(x, y)` and `reachy.mobile_base.rotate_by(x, y)`.
No test has been added as the mobile base movements are not simulated so far.
:warning: WARNING : Not tested on the robot so far
=> 393 add translate by and rotate by to mobile base

src/examples/2_goto_introduction.ipynb, src/reachy2_sdk/reachy_sdk.py, tests/units/offline/test_reachy_sdk.py, tests/units/online/test_advanced_goto_functions.py, tests/units/online/test_multiple_connections.py
Removal of is_goto_playing function from API, unit tests and notebook.
The issue being not really fixed, I'll make a new issue in the goto server repo.
=> bug #383: remove is_goto_plyaing function

src/reachy2_sdk/parts/arm.py, src/reachy2_sdk/parts/goto_based_part.py, src/reachy2_sdk/parts/head.py, tests/units/online/test_advanced_goto_functions.py
The bug was due to the `if wait` that was not supposed to be triggered with unreachable comment (i.e. there is nothing to wait for). It is fixed by a `elif`
```
response = self._goto_stub.GoToCartesian(request)
if response.id == -1:
self._logger.error(f"Target pose:\\n {target} \\nwas not reachable. No command sent.")
if wait:
self._logger.info(f"Waiting for movement with {response}.")
while not self._is_goto_finished(response):
time.sleep(0.1)
self._logger.info(f"Movement with {response} finished.")
return response
```
I've added this mechanism to all goto functions, even if the goto_joints don't raise unreachable errors for now. 
Also there is a timeout in the wait function to be sure that we don't wait forever if something goes bad on the server side (timeout is set to duration + 1 …
=> 399 robot is stuck in infinite loop using translate by with wait=true

src/reachy2_sdk/parts/goto_based_part.py
Add of a waiting condition if the id of the goto playing is -1 because the status code is still unknown. Works on unit tests and tutorials.
=> Error managing in blocking goto

src/reachy2_sdk/parts/head.py, src/reachy2_sdk/utils/utils.py, tests/units/offline/test_utils.py, tests/units/online/test_advanced_goto_functions.py
Rotate_by for the head, with frame "robot" and "head"
=> 433 add rotate for head

src/reachy2_sdk/orbita/orbita.py, src/reachy2_sdk/orbita/orbita2d.py, src/reachy2_sdk/orbita/orbita3d.py, src/reachy2_sdk/orbita/orbita_axis.py, src/reachy2_sdk/orbita/orbita_joint.py, src/reachy2_sdk/orbita/orbita_motor.py, src/reachy2_sdk/parts/arm.py, src/reachy2_sdk/parts/goto_based_part.py, src/reachy2_sdk/parts/head.py, src/reachy2_sdk/parts/joints_based_part.py, src/reachy2_sdk/utils/utils.py, tests/units/offline/test_arm.py, tests/units/offline/test_head.py, tests/units/offline/test_orbita2d.py, tests/units/offline/test_orbita3d.py
Switch from ValueError to TypeError when needed, and correction of some docstrings
=> Switch to TypeErrors 

src/reachy2_sdk/orbita/orbita.py, src/reachy2_sdk/orbita/orbita2d.py, src/reachy2_sdk/orbita/orbita3d.py, src/reachy2_sdk/parts/arm.py, src/reachy2_sdk/parts/hand.py, src/reachy2_sdk/parts/head.py, src/reachy2_sdk/parts/joints_based_part.py, src/reachy2_sdk/reachy_sdk.py
add of a boolean to check or not the positions
=> 432 thread to check the send goal positions is taking too long

src/reachy2_sdk/parts/arm.py, src/reachy2_sdk/parts/goto_based_part.py, src/reachy2_sdk/parts/head.py, tests/units/online/test_advanced_goto_functions.py
Bug of server never assigning an id to a movement (especially when the goto has a small duration)
=> add of timeout in waiting gotos

setup.cfg, src/reachy2_sdk/config/reachy_info.py
reachy.info contains information on core mode
=> 445 check core mode

src/reachy2_sdk/orbita/orbita.py, src/reachy2_sdk/orbita/orbita_joint.py, src/reachy2_sdk/parts/head.py, tests/units/online/test_advanced_goto_functions.py
Id = -1 and warning message if we do a single joint goto on a part that is off  + unit test
=> id -1 on goto_singlejoint if part is off

src/reachy2_sdk/parts/goto_based_part.py, src/reachy2_sdk/parts/head.py, src/reachy2_sdk/reachy_sdk.py
The parameters of the head goto_posture were not in the same order as the other parts, so a reachy.head.goto_posture("default") raised an error.
=> update goto_posture parameters for head

src/reachy2_sdk/parts/arm.py, src/reachy2_sdk/reachy_sdk.py, tests/units/online/test_advanced_goto_functions.py, tests/units/online/test_basic_movements.py
add _with_gripper_ parameter, to choose either the grippers open or stay the same when there is a goto_posture. Default to False, so the grippers keep the same opening.
=> 468 add gripper parameter in goto posture

src/reachy2_sdk/reachy_sdk.py, tests/units/online/conftest.py, tests/units/online/test_multiple_connections.py
On the actual SDK, every time after 10 connections to the SDK (without disconnection) then turn_on(), the stub is not working anymore : the turn_on stays stuck in self._stub.SetSpeedLimit(req) and if we add a timeout, it stays stuck in self._stub.TurnOn, etc. and we have to restart the kernel. 
They seem to be duplicate channel grpc errors. To avoid this, several modifications : 
- delete duplicate grpc channel  between __start_sync_in_bg()_ and _connect()_
- explicit deletion of the grpc channel in _disconnect()_
- Check that the instantiation to the host doesn't already exist to avoid redoing it. 
- Check that the robot isn't completely stiff before doing a _turn_on()_
=> 382 stuck in turn on

setup.cfg, src/examples/cameras.py, src/reachy2_sdk/media/camera.py, src/reachy2_sdk/sensors/lidar.py
follow up of this issue https://github.com/pollen-robotics/pollen-vision/issues/159
We use much of opencv with the SDK so it's safe to use any version.  The low version is limited to 4.8 to avoid any wrong installation that could mess up with pollen vision.
=> enhancement #450: allow opencv up to v5.0

src/examples/1_getting_started.ipynb, src/examples/2_goto_introduction.ipynb, src/examples/3_arm_and_gripper.ipynb, src/examples/4_head_control.ipynb, src/reachy2_sdk/components/antenna.py, src/reachy2_sdk/grippers/__init__.py, src/reachy2_sdk/grippers/gripper_joint.py, src/reachy2_sdk/grippers/parallel_gripper.py, src/reachy2_sdk/orbita/orbita.py, src/reachy2_sdk/orbita/orbita2d.py, src/reachy2_sdk/orbita/orbita3d.py, src/reachy2_sdk/parts/arm.py, src/reachy2_sdk/parts/hand.py, src/reachy2_sdk/parts/head.py, src/reachy2_sdk/parts/part.py, tests/units/offline/test_arm.py, tests/units/offline/test_gripper_joint.py, tests/units/offline/test_head.py, tests/units/offline/test_orbita2d.py, tests/units/offline/test_orbita3d.py, tests/units/offline/test_parallel_gripper.py, tests/units/online/test_audit.py, tests/units/online/test_hand.py
Grippers are now listed in reachy.joints
Creation of a parallel_gripper element, Hand is now abstract and the type of hand must be specified
=> 507 add gripper to reachyjoints version2

src/reachy2_sdk/components/antenna.py, src/reachy2_sdk/orbita/orbita.py, src/reachy2_sdk/parts/hand.py
For a recorded movement of 10sec on all joints, the replay using `reachy.send_goal_positions(check_positions=True)` takes more than 350sec.....
This change would make it take around 14sec instead
=> Replay with check_positions=True takes less time
